ansible -i openshift_inventory nodes:\!etcd -a 'pvcreate /dev/sdc'
ansible -i openshift_inventory nodes:\!etcd -a 'wipefs -a /dev/sdc'
ansible -i openshift_inventory nodes:\!etcd -a 'vgcreate origin-vg /dev/sdc'
ansible -i openshift_inventory nodes:\!etcd -a 'lvcreate -n origin-lv -l 100%VG origin-vg'
ansible -i openshift_inventory nodes:\!etcd -a 'mkfs.xfs /dev/mapper/origin--vg-origin--lv'
ansible -i openshift_inventory nodes:\!etcd -m shell -a 'mkdir /var/lib/origin'
ansible -i openshift_inventory nodes:\!etcd -m lineinfile -a 'path=/etc/fstab regexp=origin line="/dev/mapper/origin--vg-origin--lv /var/lib/origin xfs defaults 0 0"'
ansible -i openshift_inventory nodes:\!etcd -m shell -a 'mount -a'
