ansible -i openshift_inventory etcd -a 'yum -y install lvm2'
ansible -i openshift_inventory etcd -a 'pvcreate /dev/sdc'
ansible -i openshift_inventory etcd -a 'vgcreate etcd-vg /dev/sdc'
ansible -i openshift_inventory etcd -a 'lvcreate -n etcd-lv -l 100%VG etcd-vg'
ansible -i openshift_inventory etcd -a 'mkfs.xfs /dev/mapper/etcd--vg-etcd--lv'
ansible -i openshift_inventory etcd -m shell -a 'mkdir /var/lib/etcd'
ansible -i openshift_inventory etcd -m lineinfile -a 'path=/etc/fstab regexp=etcd line="/dev/mapper/etcd--vg-etcd--lv /var/lib/etcd xfs defaults 0 0"'
ansible -i openshift_inventory etcd -m shell -a 'mount -a'
ansible -i openshift_inventory nodes:\!etcd -a 'yum -y install lvm2'
